[project]
name = "jwt-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "datetime>=6.0",
    "fastapi>=0.141.1",
    "psycopg[binary]>=3.3.4",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.4",
    "pydentic>=0.0.1.dev3",
    "pyjwt>=2.13.0",
    "python-dotenv>=1.2.3",
    "redis>=8.1.0",
    "slowapi>=0.1.10",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.3",
]
